### ISSUE TITLE
Connecting to Neo-GUI PrivateNet

### ISSUE THREAD

**Issue by logikonline** [AxLabs/neo3-privatenet-docker#19]
Can someone share the config - I can't seem to get my Neo-GUI to connect.

**Comment by gsmachado** [comment]
hey @logikonline 
did you use docker? the command to run the docker-compose was successful?

can you use curl to get an answer from it?

**Comment by logikonline** [comment]
I do use docker, what is odd is I can query the nodes, but Neo-GUI keeps returning 0 / 0.

**Comment by logikonline** [comment]
```
`{
  "ApplicationConfiguration": {
    "Logger": {
      "Path": "Logs",
      "ConsoleOutput": true,
      "Active": true
    },
    "Storage": {
      "Engine": "LevelDBStore",
      "Path": "Data_LevelDB_5195086"
    },
    "P2P": {
      "Port": 40333,
      "WsPort": 40334,
      "MinDesiredConnections": 10,
      "MaxConnections": 40,
      "MaxConnectionsPerAddress": 3
    },
    "PluginURL": "https://github.com/neo-project/neo-modules/releases/download/v{1}/{0}.zip"
  },
  "ProtocolConfiguration": {
    "Network": 5195086,
    "MillisecondsPerBlock": 15000,
    "MaxTransactionsPerBlock": 512,
    "MemoryPoolMaxTransactions": 50000,
    "MaxTraceableBlocks": 2102400,
    "InitialGasDistribution": 5200000000000000,
    "ValidatorsCount": 1,
    "StandbyCommittee": [
        "033a4d051b04b7fc0230d2b1aaedfd5a84be279a5361a7358db665ad7857787f1b"
    ],
    "SeedList": [
        "192.168.1.57:40333"
    ]
  }
}

```
Maybe I am overthinking this?`

**Comment by gsmachado** [comment]
Let me explain you: the [`docker-compose.yml` file](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/docker-compose.yml) has the consensus node, which exposes the port 40332 (check [these lines](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/docker-compose.yml#L36-L37)).

Each node in the `docker-compose.yml` has its own configuration, for different things. You can find all the config files [here](https://github.com/AxLabs/neo3-privatenet-docker/tree/master/config). The config files are injected into each of the nodes... as an example, you can check [on these lines here](https://github.com/AxLabs/neo3-privatenet-docker/blob/master/docker-compose.yml#L28-L35).

**Comment by gsmachado** [comment]
You can use this configuration to try to use in your local Neo-CLI: https://github.com/AxLabs/neo3-privatenet-docker/blob/master/config/config-client1.privatenet3.json

**Comment by gsmachado** [comment]
Naturally, the `neo-consensus` host should be your local address, which might be `192.168.1.57` or any other address the docker interface uses.

**Comment by gsmachado** [comment]
ah, another thing is: this repo doen't expose the P2P ports... only JSON-RPC.

You might want to add the following to your `docker-compose.yml`, in the `neo-consensus` node declaration:

```
    ports:
      - "40332:40332"
      - "40333:40333"
```

Then, the P2P port `40333` will be exposed to your host machine. Then Neo-GUI will be able to connect to the network.

**Comment by gsmachado** [comment]
I might commit this to the main repo, so that it gets more accessible for people to connect with Neo-GUI.

@logikonline Please, close this issue if you could solve it! thanks!
