### ISSUE TITLE
Enable StorageDumper plugin and add new config

### ISSUE THREAD

**Issue by mialbu** [AxLabs/neo3-privatenet-docker#24]
Once Neo v3.6.0 is released, the StorageDumper plugin should be enabled again and the new config should be included.

Further, also check if StateService should be enabled again once Neo v3.6.0 is released.

https://github.com/neo-project/neo-modules/pull/790

**Comment by gsmachado** [comment]
I created a branch:
https://github.com/AxLabs/neo3-privatenet-docker/tree/feature/neo-node-3.6.0

**Comment by gsmachado** [comment]
The `StorageDumper` is ready to be added to neo3-privatenet-docker. However, there are some compilation errors still.

I prepared the `neo3-privatenet-docker` in a way that once they make the `StorageDumper` ready (compilable), then everything will be fine. We will just need to remove from this line: https://github.com/AxLabs/neo3-privatenet-docker/blob/feature/neo-node-3.6.0/docker/Dockerfile#L12

**Comment by gsmachado** [comment]
Setting this to done. Re-open if you disagree.

**Comment by mialbu** [comment]
@gsmachado Besides removing the StorageDumper from the Dockerfile, we need to add a config for the StorageDumper, don't we?

-> https://github.com/neo-project/neo-modules/pull/790/commits/452e7d1ea602da529994ea560dec4798d6aa0072#diff-994278aa228412cca5045166f7cf0fae5364b592f6ca57e26548987e1abca77b
