### ISSUE TITLE
Consensus node has no NEO or Gas

### ISSUE THREAD

**Issue by logikonline** [AxLabs/neo3-privatenet-docker#9]
Guys - love the image but their is no NEO or Gas on creation.

I may be missing something but shouldn't there be 100M there?

**Comment by logikonline** [comment]
you guys put the wrong address in the samples to look up balances.  It would help if you didn't do this.

Also, for anyone doing this from Windows, the escape values are also wrong for the samples.

For example,

`curl http://127.0.0.1:10332 -d "{\"jsonrpc\":\"2.0\",\"method\":\"getblockcount\",\"params\":[],\"id\":1}"`

**Comment by gsmachado** [comment]
@logikonline my bad. sorry for wasting some hours of yours. 😄 I'll update asap.

what would you suggest to make this repo more friendly? any feature request? let us know.

**Comment by logikonline** [comment]
It would be great if you could add an OracleService for them - since many of us are leveraging this.

Specifically setting the "Nodes": [], section

**Comment by gsmachado** [comment]
@logikonline I opened this issue: https://github.com/AxLabs/neo3-privatenet-docker/issues/12 👍 😄
